Repository stratosphererl/stratosphere, pull requests merged in 2022-11, with the labels that each got.

#46 Pull Request for Scaper DB
  ml/db/init.sql
Labels: area: ml

#53 Pull Request for Auth DB
  auth/db/README.md
  auth/db/init.sql
Labels: priority: low, area: db, area: auth

#52 Scraper-DB Pull Request
  ml/db/README.md
  ml/db/init.sql
Labels: priority: high, area: ml, area: db

#61 Dark/Light Mode and Frontend Tidy
  webapp/favicon.ico
  webapp/index.html
  webapp/package.json
  webapp/pnpm-lock.yaml
  webapp/src/App.tsx
  webapp/src/assets/logo.png
  webapp/src/components/Footer.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/Main.tsx
  webapp/src/components/ThemeSwitch.tsx
  webapp/src/components/loading.tsx
  webapp/src/components/userInput.tsx
  webapp/src/context/ThemeContext.tsx
  webapp/src/gql-components/usernames.tsx
  webapp/src/index.css
  webapp/src/replayViewer/ReplayCanvas.tsx
  webapp/src/replayViewer/SceneManager.ts
Labels: priority: medium, area: frontend
